# conda env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  {% if cookiecutter.project_packages == "All" -%}
  - fs
  - jupyter
  - pathlib
  - pandas
  - numpy
  - matplotlib
  {% endif -%}
  - pip
  {% if cookiecutter.project_packages == "All" -%}
  - pyprojroot
  {% endif -%}
  - python={{ cookiecutter.python_version }}
  - pip:
    {% if cookiecutter.desig == "Structural" -%}
    - altair==4.2.0
    - attrs==21.4.0
    - blinker==1.5
    - cachetools==5.2.0
    - certifi==2022.6.15
    - click==8.1.3
    - click-plugins==1.1.1
    - cligj==0.7.2
    - commonmark==0.9.1
    - cycler==0.11.0
    - debugpy==1.6.2
    - et-xmlfile==1.1.0
    - fonttools==4.34.4
    - forallpeople==2.6.3
    - geopandas==0.11.1
    - gitdb==4.0.9
    - GitPython==3.1.27
    - handcalcs==1.6.0
    - innerscope==0.5.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.1
    - json5==0.9.8
    - jupyter-contrib-core==0.4.0
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-kite==2.0.2
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.5.0
    - jupyterlab==3.0.0
    - jupyterlab-kite==2.0.2
    - kiwisolver==1.4.4
    - lxml==4.9.1
    - matplotlib==3.5.2
    - mkl-fft==1.3.1
    - mkl-service==2.4.0
    - more-itertools==8.14.0
    - munch==2.5.0
    - mypy==0.971
    - mypy-extensions==0.4.3
    - nodejs==0.1.1
    - openpyxl==3.0.10
    - optional-django==0.1.0
    - pandas==1.4.3
    - pandoc==2.2
    - Pillow==9.2.0
    - plumbum==1.7.2
    - ply==3.11
    - protobuf==3.20.1
    - pyarrow==9.0.0
    - pydeck==0.8.0b1
    - Pympler==1.0.1
    - pyproj==3.3.1
    - pytz-deprecation-shim==0.1.0.post0
    - PyYAML==6.0
    - QtPy==2.1.0
    - rich==12.5.1
    - scipy==1.8.1
    - seaborn==0.11.2
    - semver==2.13.0
    - Shapely==1.8.2
    - smmap==5.0.0
    - streamlit==1.12.2
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.12.0
    - tornado==6.2
    - tzdata==2022.2
    - tzlocal==4.2
    - validators==0.20.0
    - watchdog==2.1.9
    - webencodings==0.5.1
    - widgetsnbextension==3.6.1

    {% endif -%}